pipeline {
    agent any
    environment {
        BRANCH = 'testbranch' // Specify the branch
    }
    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs() // Clean up previous builds
            }
        }
        stage('Checkout') {
            steps {
                git branch: "${BRANCH}", url: 'https://github.com/I-am-saiprasad/Jenkins-Zero-To-Hero.git'
            }
        }
        stage('Verify Checkout') {
            steps {
                sh 'ls -la helloworld-app' // Verify that the files are checked out properly
            }
        }
        stage('Build') {
            steps {
                echo 'Building the project...'
                sh 'cd helloworld-app && mvn clean install' // Maven build from the correct directory
            }
        }
        stage('Run') {
            steps {
                echo 'Running the application...'
                sh 'cd helloworld-app && java -cp target/classes my-helloworld' // Adjust this based on your package structure
            }
        }
    }
}
