pipeline {
    agent any
    environment {
        BRANCH = 'testbranch' // Specify the branch
    }
    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs() // Clean up previous builds
            }
        }
        stage('Checkout') {
            steps {
                git branch: "${BRANCH}", url: 'https://github.com/I-am-saiprasad/Jenkins-Zero-To-Hero.git'
            }
        }
        stage('Verify Checkout') {
            steps {
                sh 'ls -la my-helloworld.java' // Verify that the files are checked out properly
            }
        }
        stage('Build') {
            steps {
                echo 'Building the project...'
                sh 'cd my-helloworld.java && mvn clean install' // Run Maven in the correct directory
            }
        }
    }
}
