pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'python:3.8-slim'  // Replace with your Docker image name
        GIT_REPO = 'https://github.com/I-am-saiprasad/Jenkins-ZeroToHero.git'  // Replace with your Git repository URL
        GIT_BRANCH = 'docker'  // Replace with your target branch
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: "${GIT_BRANCH}", url: "${GIT_REPO}"
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build("${DOCKER_IMAGE}")
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    dockerImage.inside {
                        sh 'pip install -r requirements.txt'
                        sh 'pytest'
                    }
                }
            }
        }
    }
}
