pipeline {
    agent {
        docker {
            image 'python:3.8-slim'  // Docker image with Python
            args '-u root:root'      // Optional: Run as root if you need additional permissions inside the container
        }
    }

    stages {
        stage('Checkout Code') {
            steps {
                // Checkout the specific branch 'docker'
                git branch: 'docker', url: 'https://github.com/I-am-saiprasad/Jenkins-Zero-To-Hero.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'pytest test_app.py'
            }
        }
    }
}
