pipeline {
    agent {
        docker {
            image 'maven:3.8.6-openjdk-11'
            args '-v /var/lib/jenkins/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                // Change to the directory containing the pom.xml file
                dir('helloworld-app') {
                    sh 'mvn clean install'
                }
            }
        }
    }
}
