pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                // Checkout the specific branch 'testbranch-python'
                git branch: 'testbranch-python', url: 'https://github.com/I-am-saiprasad/Jenkins-Zero-To-Hero.git'
            }
        }

        stage('Set up Virtual Environment') {
            steps {
                // Set up a Python virtual environment
                sh 'python3 -m venv venv'
                sh 'apt install python3.12-venv'
                sh '. venv/bin/activate'
            }
        }

        stage('Install Dependencies') {
            steps {
                // Install dependencies from requirements.txt
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                // Run the tests using pytest
                sh 'pytest test_app.py'
            }
        }
    }
}
