pipeline {
    agent any 

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'testbranch-python', url: 'https://github.com/I-am-saiprasad/Jenkins-Zero-To-Hero.git'
            }
        }

        stage('Set up Virtual Environment') {
            steps {
                // Ensure we're using bash to run the command
                sh 'python3 -m venv venv'
            }
        }

        stage('Install Dependencies') {
            steps {
                // Use bash to activate virtualenv and install dependencies
                sh 'bash -c "source venv/bin/activate && pip install -r requirements.txt"'
            }
        }

        stage('Run Tests') {
            steps {
                // Run tests using bash as well
                sh 'bash -c "source venv/bin/activate && pytest test_app.py"'
            }
        }
    }
}
