pipeline {
    agent any

    environment {
        // Define any environment variables here
        VENV_DIR = 'venv'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'flask', url: 'https://github.com/I-am-saiprasad/Jenkins-Zero-To-Hero.git'
            }
        }

        stage('Set Up Environment') {
            steps {
                sh '''
                    #!/bin/bash
                    python3 -m venv ${VENV_DIR}
                    source ${VENV_DIR}/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    #!/bin/bash
                    source ${VENV_DIR}/bin/activate
                    pytest
                '''
            }
        }

        stage('Deploy Application') {
            steps {
                sh '''
                    #!/bin/bash
                    source ${VENV_DIR}/bin/activate
                    # Add your deployment commands here
                    # For example, if you're using Gunicorn:
                    # gunicorn --bind 0.0.0.0:8000 app:app &
                '''
            }
        }
    }

    post {
        always {
            sh '''
                #!/bin/bash
                deactivate
            '''
        }
    }
}
